- name:  Setup NodeJS repos
  ansible.builtin.shell: https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed


- name: app pre-requisites
  ansible.builtin.import_tasks:
    file: app_presetup.yml


- name: Load nodejs dependencies
  ansible.builtin.shell: npm install
  args: 
      chdir: /app

- name: setup systemd service
  ansible.builtin.import_tasks:
     file: systemd_setup.yml










